name: Perform Playwright Tests Weekly

on:
  schedule:
    - cron: "0 11 * * 1,5"
  workflow_dispatch: 

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: npm install playwright @playwright/test
      
      - name: Install Playwright browsers
        run: npx playwright install chromium
      
      - name: Run Playwright tests
        run: npx playwright test
